sudo: required

language: python

python: 
- "2.7"

services:
- docker

before_install:
- docker pull centos:7
- git clone https://bitbucket.org/andyneff/rpm_specs.git specs

script:
- make test ARGS='--debug-on-fail=false --mount-repo= --mount-gpg='