FROM centos:7

RUN yum install -y createrepo rpmdevtools

RUN mkdir -p $HOME/rpmbuild/{RPMS,SRPMS,SOURCES,SPECS}

COPY repos /repos
COPY gpg /gpg

RUN printf '[rpmdocker]\nname=rpmdocker\nbaseurl=file:///home/dev/rpmbuild/RPMS\ngpgcheck=0\nenabled=1\n' > \
           /etc/yum.repos.d/rpmdocker.repo && \
    (cp -n /repos/* /etc/yum.repos.d/ || :) && \
    (cp -n /gpg/* /etc/pki/rpm-gpg/ || :)

RUN groupadd -g [{USER_GID:50}] dev && \
    useradd -u [{USER_UID:1000}] -g [{USER_GID:50}] dev && \
    echo "dev ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    sed -i '/requiretty/d' /etc/sudoers && \
    mkdir -p ~dev/rpmbuild/{SPECS,BUILD,BUILDROOT,SPECS,SOURCES,RPMS,SRPMS}

USER dev

CMD if [ "${CREATEREPO}" == "1" ]; then\
      createrepo --basedir ~/rpmbuild/RPMS /tmp && \
      rm -rvf ~/rpmbuild/RPMS/repodata && \
      mv /tmp/repodata ~/rpmbuild/RPMS/ && \
      createrepo --basedir ~/rpmbuild/SRPMS /tmp && \
      rm -rvf ~/rpmbuild/SRPMS/repodata && \
      mv /tmp/repodata ~/rpmbuild/SRPMS/; \
    fi && \
    if [ "${SPECTOOL}" == "1" ]; then \
      spectool -g -n -A -; \
    fi