FROM centos:7

RUN yum install -y yum-utils rpmdevtools

RUN mkdir -p $HOME/rpmbuild/{RPMS,SRPMS,SOURCES,SPECS}

COPY repos /repos
COPY gpg /gpg

RUN printf '[rpmdocker]\nname=rpmdocker\nbaseurl=file:///home/dev/rpmbuild/RPMS\ngpgcheck=0\nenabled=1\n' > \
           /etc/yum.repos.d/rpmdocker.repo && \
    (cp -n /repos/* /etc/yum.repos.d/ || :) && \
    (cp -n /gpg/* /etc/pki/rpm-gpg/ || :)

RUN yum makecache -y --disablerepo=rpmdocker && : [{CLEAR_CACHE:0}]
#My hope is this makes using this docker quicker. This image should be purged 
#from docker's image repository periodically to keep the cache up to day, every
#x days???

#CMD cat - > /dev/shm/rpm.spec && yum-builddep --nogpgcheck --assumeno /dev/shm/rpm.spec

COPY source /root/rpmbuild/SOURCES

CMD read rpmbuild_args && cat - > $HOME/rpmbuild/SPECS/rpm_preparse.spec && \
    set -o pipefail && \
    rpmspec -D "debug_package %{nil}" -P $HOME/rpmbuild/SPECS/rpm_preparse.spec > $HOME/rpmbuild/SPECS/rpm.spec && \
    spectool -g -n -A -C $HOME/rpmbuild/SOURCES $HOME/rpmbuild/SPECS/rpm.spec | \
      ( grep '^Getting' || : ) | sed 's/.* to \(.*\)/\1/' | \
        while IFS='' read -r filename || [ -n "${filename}" ]; do \
          truncate -s 20 "${filename}"; \
        done && \
    #creating fake missing source files
    srpm_name=$(rpmbuild -bs [{RPMBUILD_ARGS}] $HOME/rpmbuild/SPECS/rpm.spec | \
          grep "^Wrote: " | sed 's/Wrote: \(.*\)/\1/') && \
    srpm_name2=$(echo $srpm_name | sed 's|nosrc|src|') && \
    #Thank you https://bugzilla.redhat.com/show_bug.cgi?id=1166126 :(
    if [ "$srpm_name" != "$srpm_name2" ]; then \
      mv $srpm_name $srpm_name2; \
    fi && \
    (yum-builddep --nogpgcheck --assumeno ${srpm_name2} || :)
    #I still have no gpg here because... 1) SECUIRITY DOESN'T MATTER, I'm not
    #installing here, and 2) with --assumeno it will not install the gpg certs,
    #and fail. Rather then solving THAT problem, --nogpgcheck just makes sense
    #here
#Change this to yum deplist -q ${srpm_name} Returns zero on "Unsatisfies dependency"
#Example
#[computer rpmdocker]$ yum deplist srpms/caffe_local-2015.6.12-2.el7.src.rpm -q
#package: caffe_local.src 2015.6.12-2.el7
#  dependency: boost-devel >= 1.55
#   Unsatisfied dependency
#  dependency: cmake
#   provider: cmake.x86_64 2.8.11-4.el7
#  dependency: cudnn-devel
#   Unsatisfied dependency
